# version: "3.10"

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Streamlit_Frontend/Dockerfile
#     image: frontend:latest
#     ports:
#       - 8501:8501
#     networks:
#       - project_network
#     depends_on:
#       - backend
#     volumes:
#       - ./Streamlit_Frontend:/app/frontend  # Updated to map the correct directory
#     environment:
#       - PYTHONUNBUFFERED=1  # Optional for better logging in development

#   backend:
#     build:
#       context: .
#       dockerfile: FastAPI_Backend/Dockerfile
#     image: backend:latest
#     ports:
#       - 8080:8080
#     networks:
#       - project_network
#     volumes:
#       - ./FastAPI_Backend:/app/backend  # Ensure backend code is also mapped for live reloading

# networks:
#   project_network:


version: "3.10"

services:
  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/frontend  # Updated to map the correct directory
      - ./model:/app/model  # Mount the local model directory
    environment:
      - PYTHONUNBUFFERED=1  # Optional for better logging in development

  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - 8080:8080
    networks:
      - project_network
    volumes:
      - ./FastAPI_Backend:/app/backend  # Ensure backend code is also mapped for live reloading

networks:
  project_network: